web:
    build: ./web
    ports:
        - "3000:3000"
    links:
        - api
    volumes:
        - ./web:/canyons-web
        - /canyons-web/node_modules
        - ./models:/models
        - ./models:/canyons-web/node_modules/models
    environment:
        NODE_DEBUG: canyon-web
    command: bash -c 'cd /canyons-web; DEBUG=canyons supervisor -w src /canyons-web/server.js'
api:
    build: ./api
    ports:
        - "5678:5678"
    extends:
        file: ./secrets.yml
        service: api
    links:
        - db
    volumes:
        - ./api:/canyons-api
        - /canyons-api/node_modules
        - ./models:/models
        - ./models:/canyons-api/node_modules/models
    environment:
        NODE_DEBUG: canyon-api
    command: bash -c 'cd /canyons-api; DEBUG=canyons supervisor -w src /canyons-api/server.js'
db:
    volumes:
        - ./db:/docker-entrypoint-initdb.d
    image: postgres
migrations:
    build: ./migrations
    links:
        - db
    volumes:
        - ./migrations:/migrations
