web:
    build: ./web
    ports:
        - "3000:3000"
    links:
        - api
    extends:
        file: ./secrets.yml
        service: config
    environment:
        NODE_DEBUG: canyon-web
    command: bash -c 'cd /app; DEBUG=canyons node /app/server.js'
api:
    build: ./api
    ports:
        - "5678:5678"
    extends:
        file: ./secrets.yml
        service: config
    links:
        - db
    environment:
        NODE_DEBUG: canyon-api
    command: bash -c 'cd /app; DEBUG=canyons node /app/server.js'
db:
    build: ./db
migrations:
    build: ./migrations
    environment:
        - DOCKER_FIX="                                        "
    links:
        - db
    command: tail -f /dev/null

