web:
    build: ./web
    ports:
        - "3000:3000"
    links:
        - api
    volumes:
        - ./web:/app
        - /app/node_modules
        - ./models:/models
        - ./models:/app/node_modules/models
    extends:
        file: ./secrets.yml
        service: config
    environment:
        NODE_DEBUG: canyon-web
    command: bash -c 'cd /app; DEBUG=canyons supervisor -w lib /app/server.js'
api:
    build: ./api
    ports:
        - "5678:5678"
    extends:
        file: ./secrets.yml
        service: config
    links:
        - db
    volumes:
        - ./api:/app
        - /app/node_modules
        - ./models:/models
        - ./models:/app/node_modules/models
    environment:
        NODE_DEBUG: canyon-api
    command: bash -c 'cd /app; DEBUG=canyons supervisor -w lib /app/server.js'
db:
    volumes:
        - ./db:/docker-entrypoint-initdb.d
    image: postgres
migrations:
    build: ./migrations
    links:
        - db
    volumes:
        - ./migrations:/migrations
