# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision "shell", inline: <<-SHELL
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get update
  sudo apt-get -y install postgresql


  export PG_CONF="/etc/postgresql/9.3/main/postgresql.conf"
  export PG_HBA="/etc/postgresql/9.3/main/pg_hba.conf"

  sudo -u postgres sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" "$PG_CONF"
  sudo -u postgres sh -c "echo 'client_encoding = utf8' >> $PG_CONF"
  sudo -u postgres sh -c "echo 'host    all             all             all                     md5' >> $PG_HBA"
  sudo service postgresql restart

  export DB=canyons
  export USER=canyons
  export PASS=canyons
  sudo -u postgres psql -c "CREATE USER $USER WITH PASSWORD '$PASS';"
  sudo -u postgres psql -c "CREATE DATABASE $DB WITH OWNER=$USER
                                                     LC_COLLATE='en_US.utf8'
                                                     LC_CTYPE='en_US.utf8'
                                                     ENCODING='UTF8'
                                                     TEMPLATE=template0;"
  SHELL

  config.vm.network :forwarded_port, guest: 5432, host: 5432

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
end
